GET http://localhost:3001/api/persons/5e899846a68acf5a08d59623
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Lupu Ankka",
    "number": "11-11"
}

###

PUT http://localhost:3001/api/persons/5e907301ab4ddb1bf80158b0
Content-Type: application/json

{
    "name": "Lupu Ankka",
    "number": "11-11-11"
}

###

DELETE http://localhost:3001/api/persons/5e907301ab4ddb1bf8015b0b

###

GET http://localhost:3001/api/persons
