
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5e899846a68acf5a08d59623

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Hupu",
    "number": "100"
}

###

PUT http://localhost:3001/api/persons/5e906e6805f2651e1860b3dd
Content-Type: application/json

{
    "name": "Lupu Ankka",
    "number": "11-11"
}

###

DELETE http://localhost:3001/api/persons/5e907301ab4ddb1bf8015b0b

###


GET http://localhost:3001/info
